### ISSUE TITLE
Upgrade quarkus 3.0.0.Final

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#494] opened 2023-04-26 17:02 UTC

**Comment by shivam-sharma7** [comment] 2023-04-26 17:31
@jesperpedersen and @johnaohara what is your thought?

**Comment by jesperpedersen** [comment] 2023-04-27 06:03
No near time plans for this - feel free to work on it.

Closed as a duplicate of #333

**Closed by jesperpedersen** 2023-04-27 06:03 UTC
Labels: feature
