### ISSUE TITLE
App.tsx replace `Switch `  with  `Routes`

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#421] opened 2023-03-15 02:24 UTC

**Comment by rukundob451** [comment] 2023-04-28 05:37
Hello @shivam-sharma7, is this issue still available?

**Comment by shivam-sharma7** [comment] 2023-04-28 05:56
yes

**Comment by rukundob451** [comment] 2023-04-28 09:30
@shivam-sharma7, kindly need some more context to this issue?

**Comment by johnaohara** [comment] 2023-04-28 09:41
@shivam-sharma7 this issue looks like a duplicate of https://github.com/Hyperfoil/Horreum/issues/419?

**Closed** 2023-04-28 11:18 UTC
Labels: bug
