### ISSUE TITLE
Upgrade quinoa 2.0.3

### ISSUE THREAD

**Issue by shivam-sharma7** [Hyperfoil/Horreum#495] opened 2023-04-26 17:34 UTC

**Comment by shivam-sharma7** [comment] 2023-04-26 17:34
@jesperpedersen and @johnaohara what is your thought?

**Comment by jesperpedersen** [comment] 2023-04-27 06:04
Quinoa 2 is part of Quarkus 3.

Closed as a duplicate of #333

**Closed by jesperpedersen** 2023-04-27 06:04 UTC
Labels: feature
