### ISSUE TITLE
Docs on Running Horreum locally now outdated.

### ISSUE THREAD

**Issue by whitingjr** [Hyperfoil/Horreum#891] opened 2023-09-26 10:29 UTC
Following the PR[#603 Implement Horreum Dev Services](https://github.com/Hyperfoil/Horreum/pull/603) being pulled in the Horreum documentation site needs updating. To keep beginner instructions relevant.

**Comment by johnaohara** [comment] 2024-01-12 06:33
Duplicate of #788

**Closed by johnaohara** 2024-01-12 06:33 UTC
Labels: documentation
