### ISSUE TITLE
AlertingServiceImpl: NPE

### ISSUE THREAD

**Issue by jesperpedersen** [Hyperfoil/Horreum#378] opened 2023-02-14 14:51 UTC
```
ERROR [io.hyp.too.hor.ser.ErrorReporter] (executor-thread-2) Exception in handler for message bus channel datapoint/new, message DataPoint.Event{dataPoint=374|55@2023-02-14T14:30:08.994Z: 1.0, notify=false}

: java.lang.NullPointerException
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl.onNewDataPoint(AlertingServiceImpl.java:583)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass.onNewDataPoint$$superforward1(Unknown Source)
	at io.hyperfoil.tools.horreum.svc.AlertingServiceImpl_Subclass$$function$$19.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor.intercept(RolesInterceptor.java:70)
	at io.hyperfoil.tools.horreum.server.RolesInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:50)
```

**Comment by whitingjr** [comment] 2023-09-29 15:22
@jesperpedersen this is a duplicate of #539 which has been fixed.

**Closed by whitingjr** 2023-09-29 15:22 UTC
Labels: bug
